# -* encoding: utf-8 *-
from typing import Dict, Any, Sequence, Optional


def getenv_bool(setting_name: str) -> bool: ...
def factorise(custom_settings: Optional[Sequence[str]]=None) -> Dict[str, Any]: ...
